on: 
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  fetch-hosts:
    name: Fetch and Prepare Hosts
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.set-hosts.outputs.hosts }}  # Store hosts as output for next job
    steps:
      - name: Fetch host list from API
        id: fetch-hosts
        run: |
          curl -s "https://api.coursesprout.com/debug-comment/sob" | jq -c '.hosts' > hosts.json

      - name: Set Hosts Output
        id: set-hosts
        run: |
          echo "hosts=$(cat hosts.json)" >> $GITHUB_OUTPUT

  log-hosts:
    name: Log Hosts
    needs: fetch-hosts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJson(needs.fetch-hosts.outputs.hosts).*.ip }}
    steps:
      - name: Log host details
        run: |
          echo "Processing Host: ${{ matrix.host }}"
